server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.27.187.236:3306/gp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=CST
    username: root
    password: gtis
mybatis:
  mapper-locations: classpath:mapper/*.xml